- .github/actions/setup/action.yml
- mise.lock
- mise.toml
- add lockfile for Mise: `mise.lock`
- disable Node.js GPG verification in `mise.toml` (it fails even locally)
> feat: add mise.lock

- apps/beeai-cli/src/beeai_cli/__init__.py
- apps/beeai-cli/src/beeai_cli/commands/agent.py
- apps/beeai-cli/src/beeai_cli/commands/env.py
- apps/beeai-cli/src/beeai_cli/commands/provider.py
- apps/beeai-cli/src/beeai_cli/commands/tool.py
- apps/beeai-server/src/beeai_server/adapters/filesystem.py
- apps/beeai-server/src/beeai_server/adapters/interface.py
- apps/beeai-server/src/beeai_server/application.py
- apps/beeai-server/src/beeai_server/bootstrap.py
- apps/beeai-server/src/beeai_server/configuration.py
- apps/beeai-server/src/beeai_server/crons/reload_external_changes.py
- apps/beeai-server/src/beeai_server/crons/sync_registry_providers.py
- apps/beeai-server/src/beeai_server/domain/model.py
- apps/beeai-server/src/beeai_server/exceptions.py
- apps/beeai-server/src/beeai_server/routes/dependencies.py
- apps/beeai-server/src/beeai_server/routes/env.py
- apps/beeai-server/src/beeai_server/routes/provider.py
- apps/beeai-server/src/beeai_server/schema.py
- apps/beeai-server/src/beeai_server/services/env.py
- apps/beeai-server/src/beeai_server/services/mcp_proxy/provider.py
- apps/beeai-server/src/beeai_server/services/provider.py
closes: #141 
Added global environment variable management.
A provider can declare required and optional environment variables in the manifest:
```
manifestVersion: 1
driver: container
image: test-manifest:local
serverType: http
mcpTransport: sse
mcpEndpoint: /sse
env:
- required: True
name: 'TEST_VAR'
description: 'my test variable'
```
- A provider with this manifest can be added and will be executed even if required variables are not fullfiled.  
- There will be "dummy" values supplied for all unfulfilled required values. This naive approach will let us list agents in some cases, but there may still be problems when there is for example validation of env variables.
You can get the list of missing required variables in `beeai list provider`.
UI can get this information using the …
> feat(server): add  global env variables management and provisioning

- apps/beeai-ui/src/modules/agents/components/AgentCard.module.scss
- apps/beeai-ui/src/modules/agents/components/AgentCard.tsx
- apps/beeai-ui/src/modules/agents/components/AgentDetail.module.scss
- apps/beeai-ui/src/modules/agents/components/AgentDetail.tsx
- apps/beeai-ui/src/modules/agents/components/AgentsList.module.scss
Refs: https://github.com/i-am-bee/beeai/issues/176
Most notable change:
Decreased the size of the agent's **name** and **description**.
Other changes:
- the **line** under the agent's **name** is reduced in height to match the smaller font size,
- spacing between the **cards** slightly reduced,
- spacing between the elements inside the **card** updated (more space above tag list),
- fixed `<AgentCard.Skeleton>` where CSS class should be set to the container,
- spacing for the `.divider` line in `<AgentDetail>` is made much smaller.
Showcases the updates and several page refreshes.
https://github.com/user-attachments/assets/b46a6125-e481-4ece-8ac9-4d583bdf2d8f
> chore(ui): update typography

- apps/beeai-web/src/acp/client.ts
- apps/beeai-web/src/acp/native-fetch.ts
- apps/beeai-web/src/instrumentation.ts
Do not use `unstable_cache` from nextjs that caches result agresively, just use `cache` from react to dedupe calls in single request
Because nextjs patched fetch doesn't play nicely with acp client implementation we provide native nodejs fetch to the underlying eventsource
> fix(web): listAgents on every request for true SSR

- apps/beeai-web/.env.example
- apps/beeai-web/src/acp/client.ts
- apps/beeai-web/src/constants.ts
I renamed `BEEAI_HOST` to `ACP_CLIENT_SERVER_URL` since the full URL to the ACP client server is expected now.
> chore(web): rename ACP_CLIENT_SERVER_URL env

- apps/beeai-web/next.config.ts
- apps/beeai-web/src/components/MainNav/MainNav.module.scss
- apps/beeai-web/src/components/MainNav/MainNav.tsx
Disable CSS chunking due to persistent nextjs bug with ordering of css and this seems to help partially.
Nextjs in production build only! puts global styles last so it messes up css specificity.
We get css modules styles twice but atleast the second css file overwrites them in correct order.
I think it's actually two issues, first is with sideEffects and external packages, because beeai-ui doesn't
have `sideEffects: false` in package.json and I don't wanna add it because it's vite app, not a library
and we have single `index.ts` in it that exports everything, nextjs bundler doesn't tree shake and sees
all styles as required in a root layout. Having separate exports in package.json helps but doesn't mitigate
the issue completely see second issue bellow.
The second issue is IMHO when the …
> fix(web): css order and add active links

- agents/community/aider-agent/beeai-provider.yaml
- agents/community/aider-agent/src/aider_agent/agent.py
- agents/community/autogen-agents/beeai-provider.yaml
- agents/community/autogen-agents/src/autogen_agents/configuration.py
- agents/community/autogen-agents/src/autogen_agents/literature_review/team.py
- agents/community/autogen-agents/uv.lock
- agents/community/crewai-agents/beeai-provider.yaml
- agents/community/crewai-agents/src/crewai_agents/configuration.py
- agents/community/crewai-agents/uv.lock
- agents/community/gpt-researcher-agent/beeai-provider.yaml
- agents/community/gpt-researcher-agent/gpt_researcher_agent/configuration.py
- agents/community/langgraph-agents/beeai-provider.yaml
- agents/community/langgraph-agents/pyproject.toml
- agents/community/langgraph-agents/src/langgraph_agents/configuration.py
- agents/community/langgraph-agents/src/langgraph_agents/ollama_deep_researcher/configuration.py
- agents/community/langgraph-agents/src/langgraph_agents/ollama_deep_researcher/graph.py
- agents/community/langgraph-agents/uv.lock
- agents/official/agent-docs-creator/beeai-provider.yaml
- agents/official/agent-docs-creator/src/agent-docs-creator.ts
- agents/official/agent-docs-creator/src/config.ts
- agents/official/beeai-framework/beeai-provider.yaml
- agents/official/beeai-framework/src/chat/chat.ts
- agents/official/beeai-framework/src/config.ts
- agents/official/beeai-framework/src/content-judge/content-judge.ts
- agents/official/beeai-framework/src/podcast-creator/podcast-creator.ts
- agents/official/beeai-supervisor/beeai-provider.yaml
- agents/official/beeai-supervisor/src/server.ts
- docs/get-started/installation.mdx
Unify environment variables in agents. Now, all* of the agents are unified to use env vars `LLM_API_KEY`, `LLM_API_BASE` and `LLM_MODEL`, assuming an OpenAI-compatible endpoint.
This could eventually help us implement our own OpenAI-compatible endpoint proxy, but for now it at least unifies most of the agents under a single interface.
Yeah, this potentially limits compatibility with extra features of some providers. But it seems like a good tradeoff at this point.
~*`gpt-researcher` uses an embedding endpoint which is not available on Groq, so I left it at the current state (Ollama only) for the time being.~
> refactor(agents): unify env

- apps/beeai-web/src/app/agents/AgentsFilteredView.tsx
- apps/beeai-web/src/app/agents/AgentsView.tsx
- apps/beeai-web/src/app/agents/page.tsx
Refs: https://github.com/i-am-bee/beeai/issues/177
Fixes `undefined` **default values**. Using `<AgentsFiltersProvider>`.
> fix(web): undefined defaultValues

- apps/beeai-ui/src/modules/compose/components/ComposeStepListItem.tsx
- apps/beeai-ui/src/modules/compose/contexts/ComposeProvider.tsx
- apps/beeai-ui/src/modules/compose/types.ts
Visual feedback of step progress in the sequential workflow was broken because some agents don’t send notifications, leaving the UI without data to indicate when a step starts executing. However, a success notification is sent (without a step index), so I now process them sequentially—ending the currently pending step and starting a new one if available.
> fix(ui): track sequential run steps progress

- apps/beeai-ui/src/components/MainNav/MainNav.tsx
- apps/beeai-ui/src/components/MainNav/TracesTooltip.tsx
- apps/beeai-ui/src/components/MainNav/queries/usePhoenix.ts
- apps/beeai-ui/src/components/Tooltip/Tooltip.module.scss
- apps/beeai-ui/vite.config.ts
I added a new "Traces" tab to the menu, that is enabled only when the Phoenix server is running. Otherwise, the disabled item with the tooltip with the link to the Observability documentation part is visualized. 
It works only locally. (the Phoenix server target is set to `http://localhost:6006`) the same way as for mcp and API proxy. See `vite.config.ts` for more details. 
The state is checked every 60 seconds.
> feat(phoenix): add traces button (#241)

- apps/beeai-cli/src/beeai_cli/commands/env.py
This branch fixes the name of the locally created `ollama` model when adding a non-default context length
> fix: Use the selected model name for the modified long-context model

- apps/beeai-ui/src/modules/run/api/types.ts
- apps/beeai-ui/src/modules/run/contexts/hands-off/HandsOffProvider.tsx
The text in delta should always be a string, but the agent could actually return undefined. This PR handles it.
> fix(ui): handling agent's undefined text in delta

- agents/official/agent-docs-creator/package-lock.json
- agents/official/agent-docs-creator/package.json
- agents/official/beeai-framework/package-lock.json
- agents/official/beeai-framework/package.json
I badly parsed the memory object on agent's error/retry events. This error is fixed in the latest package version. 
See https://github.com/Arize-ai/openinference/blob/main/js/packages/openinference-instrumentation-beeai/CHANGELOG.md#patch-changes
> fix(instrumentation): agent error and retry events

- .github/workflows/common.yml
- agents/community/marketing-strategy/pyproject.toml
- agents/community/marketing-strategy/src/marketing_strategy/server.py
- agents/community/marketing-strategy/uv.lock
- apps/beeai-cli/tasks.toml
- apps/beeai-server/src/beeai_server/domain/collector/base.yaml
- apps/beeai-server/tasks.toml
- mise.toml
- packages/acp-python-sdk/tasks.toml
- packages/beeai-sdk/tasks.toml
- pyproject.toml
- uv.lock
I updated the collector filter to `- not(IsMatch(instrumentation_scope.name, "^openinference\\.instrumentation\\..*") or IsMatch(instrumentation_scope.name, "^@arizeai/openinference-instrumentation-.*") or instrumentation_scope.name == "crewai.telemetry")`. This filter should pass only spans from openiference packages.
I removed the `LangChainInstrumentor` from the crewAI `marketing-strategy` agent.
> feat(instrumentation): filter openinference spans

- helm/beeai-platform/templates/agent/deployment.yaml
Define env variable HOME to /tmp'
1. To make sure container creation successful in case of strict OpenShift environment avoiding Permission denied issues like: 
a. Permission denied: '/.mem0' 
b. error: failed to create directory `/.cache/uv`: Permission denied (os error 13)
Signed-off-by: chandra.-potula <potula.chandureddy@gmail.com>
> Define env variable HOME

- CONTRIBUTING.md
- apps/beeai-cli/data/lima-vm.yaml
- apps/beeai-cli/src/beeai_cli/commands/platform.py
- apps/beeai-server/Dockerfile
- apps/beeai-server/tasks.toml
- Allow running `beeai-platform` with a locally built image (only `beeai-server` for now).
- Add more switches to `beeai platform run`: `--import-images` to load images from `~/.beeai/images`, and `--set <key>=<value>` to set Helm chart values.
- Reduce image size of `beeai-platform` from 850 MB to 150 MB (most dependencies were for bare metal providers which we don't support anymore)
- Improve docs on the development setup
> feat(beeai-cli): platform image load

- apps/beeai-cli/src/beeai_cli/commands/env.py
Small update to beeai-cli to point to granite3.2:8b during env setup with Ollama.
Closes #656
> Updated default model for ollama setup to granite

- apps/beeai-ui/src/modules/runs/components/AgentModel.tsx
- apps/beeai-ui/src/modules/variables/api/queries/useListVariables.ts
When the platform is deployed with authentication, the `/variables` endpoint fails — this is expected behavior, as it returns sensitive data (like API keys) and is intentionally restricted.
The frontend currently calls this endpoint on the agent run page to retrieve the current model via environment variables. This is only a temporary workaround until the API starts returning the model directly.
This PR hides the error toast when the fetch fails, as the failure is expected.
> fix(ui): suppress error toast when variables fetch fails

- agents/official/beeai-supervisor/src/supervisor/platform-sdk.ts
- apps/beeai-ui/.env.example
- apps/beeai-ui/README.md
- apps/beeai-ui/package.json
- apps/beeai-ui/src/components/AppHeader/AppHeader.tsx
- apps/beeai-ui/src/components/AppHeader/AppHeaderNav.module.scss
- apps/beeai-ui/src/components/AppHeader/AppHeaderNav.tsx
- apps/beeai-ui/src/modules/nav/parseNav.ts
- apps/beeai-ui/src/modules/nav/schema.ts
- apps/beeai-ui/src/utils/files/loadFile.ts
- apps/beeai-ui/src/utils/files/loadJson.ts
- apps/beeai-ui/src/utils/modules/loadJson.ts
- apps/beeai-ui/src/utils/vite-constants.ts
- apps/beeai-ui/src/vite-env.d.ts
- apps/beeai-ui/vite.config.ts
Allow for **custom navigation** in the header by adding a `nav.json` file to the root of the UI project.
The file is <ins>optional</ins>. If _omitted_ or _invalid_, standard header is used (which displays the agent's name and a detail button).
```json
[
{
"label": "Playground",
"url": "/",
"isActive": true
},
{
"label": "Cookbooks",
"url": "https://example.com/cookbooks",
"isExternal": true
},
{
"label": "Docs",
"url": "https://example.com/docs",
"isExternal": true
},
{
"label": "Download Granite",
"url": "https://example.com/download-granite",
"isExternal": true,
"position": "end"
}
]
```
<br><br>
---
- Prefix envs with `VITE_` (so can customize `VITE_API_SERVER_TARGET` via `loadEnv()`)
- Allow for custom `VITE_API_SERVER_TARGET`
- Use `localhost`
- Update `.env.example`
> feat(ui): custom header nav

- docs/introduction/installation.mdx
> [!WARNING]
> Merge only after releasing the bundled `limactl` -- Linux instructions have changed.
Put all installation instructions in a single list. (Adds a bit of redundancy in code but it looks better visually.) Unify all platforms under `uv`.
> docs: improve installation instructions

- CONTRIBUTING.md
Fixes a broken Markdown anchor link in `CONTRIBUTING.md`.
The original link used spaces and capitalization, which prevented it from correctly linking to the "Running and debugging individual components" section. This update uses a GitHub-compatible anchor format.
> docs(contributing): fix anchor link in section reference

- apps/beeai-server/src/beeai_server/api/routes/llm.py
Expose `response_format` for providers that support it
Fixes #839
> feat(beeai-server): add response format to LLM proxy

- apps/beeai-ui/src/modules/runs/chat/Message.tsx
- apps/beeai-ui/src/modules/runs/contexts/agent-run/AgentRunProvider.tsx
- apps/beeai-ui/src/modules/runs/files/components/FileCard.module.scss
- apps/beeai-ui/src/modules/runs/utils.ts
Closes #886 
This PR addresses:
- Long filenames in chat messages are now properly truncated.
- Only `content` with `content_type` of "text/plain "or "image/*" is added to the message content.
- If a message fails, any previously successful message parts remain visible.
- The filename of the uploaded file is now sent in the `name` field of the MessagePart.
- If no message is returned from the agent and the run completes, a “Failed” status is shown.
Also resolves #760:
- If no agent with supported UI is found on the platform, we now explicitly display a message instead of showing an infinite spinner.
> fix(ui): minor chat bugs and improvs

- apps/beeai-ui/.env.example
- apps/beeai-ui/README.md
- apps/beeai-ui/src/components/AppHeader/AppHeaderNav.module.scss
- apps/beeai-ui/src/components/AppHeader/AppHeaderNav.tsx
- apps/beeai-ui/src/components/AppHeader/AppName.module.scss
- apps/beeai-ui/src/components/AppHeader/AppName.tsx
- apps/beeai-ui/src/components/AppHeader/SidebarButton.module.scss
- apps/beeai-ui/src/components/AppHeader/SidebarButton.tsx
- apps/beeai-ui/src/components/CustomNav/CustomNav.tsx
- apps/beeai-ui/src/components/SidePanel/Nav.module.scss
- apps/beeai-ui/src/components/SidePanel/SidePanel.module.scss
- apps/beeai-ui/src/components/SidePanel/SidePanel.tsx
- apps/beeai-ui/src/components/layouts/MainNav.tsx
- apps/beeai-ui/src/modules/nav/groupNavItems.ts
- apps/beeai-ui/src/modules/nav/isActive.ts
- apps/beeai-ui/src/modules/nav/parseNav.ts
- apps/beeai-ui/src/modules/nav/schema.ts
**ONLY** if having `NAV_ITEMS`:
- _Show_ **"start"** items in `<MainNav>`
- _Show_ **"start"** items in `<AppHeaderNav>` on `md+` only
- _Show_ `<SidebarButton>` on `<md` only
- _Auto-close_ `<MainNav>`
Also related to `NAV_ITEMS`:
- Update schema for nav items (`.activePathnames`, `.target`)
- Add helpers: `groupNavItems()`, `isActive()`
- Fix **parsing** in `parseNav()`
Other changes:
- Move app name to `<AppName>`
---
For a quick test, use:
```
NEXT_PUBLIC_NAV_ITEMS='[{"label":"Playground","url":"/","activePathnames":["/","/agents"]},{"label":"Cookbooks","url":"/docs/cookbooks","isExternal":true,"target":"_self"},{"label":"Docs","url":"/docs","isExternal":true,"target":"_self"},{"label":"Download Granite","url":"https://huggingface.co/ibm-granite/granite-3.3-8b-instruct","isExternal":tr …
```
> feat(ui): update nav items

- apps/beeai-ui/.env.example
- apps/beeai-ui/next.config.ts
- apps/beeai-ui/src/acp/index.ts
- apps/beeai-ui/src/api/index.ts
- apps/beeai-ui/src/app/api/[...path]/route.ts
- apps/beeai-ui/src/app/layout.tsx
- apps/beeai-ui/src/utils/api/getBaseUrl.ts
- apps/beeai-ui/src/utils/constants.ts
Support **custom** `basePath`.
Ensure the **correct** _API URL_ is constructed when called from either the **server** or the **client**.
<br>
1. Set:
```
NEXT_PUBLIC_BASE_PATH='/granite/playground'
```
<br>
2. Run:
```
$ mise beeai-ui:run:dev
```
<br>
3. Open: http://localhost:3000/granite/playground
<br>
---
<br>
1. Set:
```
NEXT_PUBLIC_BASE_PATH='/granite/playground'
```
<br>
2. Run:
```
$ mise beeai-ui:build:nextjs
$ mise beeai-ui:run
```
<br>
3. Open: http://localhost:3000/granite/playground
<br><br><br>
- API calls use the correct base path and work (both "ACP" and "API").
- Favicon correctly set.
> feat(ui): support custom basePath

- apps/beeai-ui/src/modules/runs/chat/ChatAgentMessage.module.scss
- apps/beeai-ui/src/modules/runs/chat/ChatMessagesView.module.scss
- apps/beeai-ui/src/modules/runs/components/NewSessionButton.module.scss
- apps/beeai-ui/src/modules/runs/components/NewSessionButton.tsx
This PR includes:
- closes #1096
- Updated message hover color, so the code blocks don't blend with the background
- minor adjustment of New session button to prevent it from sticking to to the top padding, when underlying message is hovered
> fix(ui): new session button position

- apps/beeai-ui/src/components/Spinner/Spinner.module.scss
Added additional 1px padding to the animation container so the resized Lottie animation is not cropped in size `sm` due to its svg animation resizing glitch
Closes: #1132
Signed-off-by: jayolee <43683780+jayolee@users.noreply.github.com>
> style: spinner getting cropped in small size fix

- apps/beeai-sdk/src/beeai_sdk/server/agent.py
- apps/beeai-sdk/src/beeai_sdk/server/app.py
- apps/beeai-sdk/src/beeai_sdk/server/server.py
URLs in the agent card must sometimes be different from the server's host+port to enable reverse proxies (cluster setting).
We can't dynamically resolve this URL due to a limitation in A2A interface https://github.com/a2aproject/a2a-python/blob/b2e3a29607cdac9b555e7fd188048c67dd72dc67/src/a2a/server/apps/rest/fastapi_app.py#L52. Note that this limitation might be intended as the agent card should be mostly static.
Therefore we at least allow SDK users to setup the values in the agent card.
> chore(sdk): Allow setting agent card interfaces

- apps/beeai-ui/src/@types/utils.ts
- apps/beeai-ui/src/modules/platform-context/api/index.ts
- apps/beeai-ui/src/modules/platform-context/api/mutations/useUpdateContextMetadata.ts
- apps/beeai-ui/src/modules/platform-context/api/types.ts
- apps/beeai-ui/src/modules/platform-context/contexts/PlatformContextProvider.tsx
We need to use PATCH endpoint to update context metadata. The original PUT was replacing all stored values.
> fix(ui): use patch instead of put for update context metadata
