- packages/acp-python-sdk/README.md
- packages/acp-typescript-sdk/README.md
closes https://github.com/i-am-bee/beeai/issues/43
> chore(acp): add disclaimer for SDKs

- agents/community/gpt-researcher-agent/beeai-provider.yaml
- agents/official/bee-agent-framework/beeai-provider.yaml
- agents/official/bee-agent-framework/src/server.ts
- apps/beeai-cli/src/beeai_cli/commands/provider.py
- apps/beeai-server/src/beeai_server/adapters/filesystem.py
- apps/beeai-server/src/beeai_server/application.py
- apps/beeai-server/src/beeai_server/bootstrap.py
- apps/beeai-server/src/beeai_server/configuration.py
- apps/beeai-server/src/beeai_server/crons/reload_provider_container.py
- apps/beeai-server/src/beeai_server/crons/sync_registry_providers.py
- apps/beeai-server/src/beeai_server/domain/model.py
- apps/beeai-server/src/beeai_server/routes/provider.py
- apps/beeai-server/src/beeai_server/services/mcp_proxy/provider.py
- apps/beeai-server/src/beeai_server/services/provider.py
- apps/beeai-server/src/beeai_server/utils/github.py
- apps/beeai-server/src/beeai_server/utils/managed_server_client.py
- apps/beeai-server/src/beeai_server/utils/periodic.py
- apps/beeai-server/src/beeai_server/utils/utils.py
- mise.toml
- packages/beeai-sdk/src/beeai_sdk/providers/agent.ts
- provider-registry.yaml
> feat(server): add official provider registry

- agents/official/bee-agent-framework/package.json
- agents/official/bee-agent-framework/src/server.ts
- apps/beeai-cli/src/beeai_cli/commands/agent.py
- pnpm-lock.yaml
closes https://github.com/i-am-bee/beeai/issues/102
supports https://github.com/i-am-bee/beeai/issues/103
> feat(agents): replace Streamlit agent with Bee

- agents/official/bee-agent-framework/package.json
- agents/official/bee-agent-framework/src/server.ts
- packages/beeai-sdk/src/beeai_sdk/schemas/config.py
- packages/beeai-sdk/src/beeai_sdk/schemas/config.ts
- pnpm-lock.yaml
> feat: add tool selection for bee agent

- agents/official/bee-agent-framework/src/server.ts
- apps/beeai-ui/package.json
- apps/beeai-ui/src/hooks/useImmerWithGetter.ts
- apps/beeai-ui/src/modules/run/chat/types.ts
- apps/beeai-ui/src/modules/run/contexts/ChatProvider.tsx
- pnpm-lock.yaml
> feat(ui): switch chat agent to array of messages

- agents/community/crewai-agents/beeai-provider-unmanaged.yaml
- agents/community/crewai-agents/beeai-provider.yaml
- agents/community/crewai-agents/pyproject.toml
- agents/community/crewai-agents/src/crewai_agents/__init__.py
- agents/community/crewai-agents/src/crewai_agents/configuration.py
- agents/community/crewai-agents/src/crewai_agents/marketing_posts/config/agents.yaml
- agents/community/crewai-agents/src/crewai_agents/marketing_posts/config/tasks.yaml
- agents/community/crewai-agents/src/crewai_agents/marketing_posts/crew.py
- agents/community/crewai-agents/src/crewai_agents/server.py
- agents/community/crewai-agents/uv.lock
- pnpm-lock.yaml
- provider-registry.yaml
- pyproject.toml
> feat(agents): add marketing strategy crewai agent

- packages/beeai-sdk/package.json
- packages/beeai-sdk/pyproject.toml
- packages/beeai-sdk/src/beeai_sdk/providers/agent.ts
- pnpm-lock.yaml
- uv.lock
> fix(sdk): improve stability of agent provider server in node

- .github/workflows/beeai-server.yml
- apps/beeai-server/Dockerfile
> feat(server): add CI/CD pipeline

- apps/beeai-cli/src/beeai_cli/__init__.py
- apps/beeai-cli/src/beeai_cli/api.py
- apps/beeai-cli/src/beeai_cli/async_typer.py
- apps/beeai-cli/src/beeai_cli/commands/agent.py
- apps/beeai-cli/src/beeai_cli/commands/env.py
- apps/beeai-cli/src/beeai_cli/commands/provider.py
- apps/beeai-cli/src/beeai_cli/commands/tool.py
- apps/beeai-cli/src/beeai_cli/utils.py
> feat(cli): improve rendering and usage

- agents/official/beeai-framework/src/content-judge.ts
- agents/official/beeai-framework/src/podcast-creator.ts
Refs https://github.com/i-am-bee/beeai/issues/169
> feat(agent): add input example as metadata

- agents/community/langgraph-agents/README.md
- agents/community/langgraph-agents/beeai-provider.yaml
- agents/community/langgraph-agents/pyproject.toml
- agents/community/langgraph-agents/src/langgraph_agents/configuration.py
- agents/community/langgraph-agents/src/langgraph_agents/langgraph.json
- agents/community/langgraph-agents/src/langgraph_agents/ollama_deep_researcher/configuration.py
- agents/community/langgraph-agents/src/langgraph_agents/ollama_deep_researcher/graph.py
- agents/community/langgraph-agents/src/langgraph_agents/ollama_deep_researcher/prompts.py
- agents/community/langgraph-agents/src/langgraph_agents/ollama_deep_researcher/state.py
- agents/community/langgraph-agents/src/langgraph_agents/ollama_deep_researcher/utils.py
- agents/community/langgraph-agents/src/langgraph_agents/server.py
- agents/community/langgraph-agents/uv.lock
- provider-registry.yaml
Refs https://github.com/i-am-bee/beeai/issues/116
> feat(agents): add langgraph community agents provider

- .github/workflows/beeai-web.yml
- apps/beeai-ui/package.json
- apps/beeai-web/Dockerfile
- apps/beeai-web/next.config.ts
- apps/beeai-web/package.json
- apps/beeai-web/src/app/page.tsx
- apps/beeai-web/src/components/layouts/AppLayout.tsx
- apps/beeai-web/src/styles/_common.scss
- apps/beeai-web/src/styles/style.scss
- pnpm-lock.yaml
> chore(web): build and package rename

- apps/beeai-ui/index.html
> feat(ui): set SVG favicon

- apps/beeai-web/src/acp/client.ts
- apps/beeai-web/src/app/agents/[name]/page.tsx
- apps/beeai-web/src/app/agents/page.tsx
- apps/beeai-web/src/constants.ts
> fix(web): force dynamic build for agent pages

- apps/beeai-web/src/acp/client.ts
- apps/beeai-web/src/constants.ts
> fix(web): move BEEAI_HOST env check

- apps/beeai-ui/src/modules/agents/components/AgentDetail.tsx
- apps/beeai-ui/src/modules/agents/components/AgentTags.module.scss
- apps/beeai-ui/src/modules/agents/components/AgentTags.tsx
Refs: https://github.com/i-am-bee/beeai/issues/176
Shows GitHub link, if provided. Only on the **detail** page.
> feat(ui): show GitHub link in detail

- apps/beeai-cli/src/beeai_cli/async_typer.py
- apps/beeai-cli/src/beeai_cli/commands/agent.py
- apps/beeai-cli/src/beeai_cli/commands/env.py
- apps/beeai-cli/src/beeai_cli/commands/provider.py
- apps/beeai-cli/src/beeai_cli/commands/tool.py
- apps/beeai-cli/src/beeai_cli/utils.py
closes: #215
closes: #216 
ref: #182
> feat(cli): improve agent detail page

- packages/beeai-sdk/src/beeai_sdk/schemas/text.py
- packages/beeai-sdk/src/beeai_sdk/schemas/text.ts
Refs https://github.com/i-am-bee/beeai/issues/222
> feat(sdk): rename promptInput to textInput

- apps/beeai-ui/tasks.toml
To run the task:
```
$ mise beeai-ui:preview
```
> feat(ui): add preview task

- apps/beeai-cli/src/beeai_cli/commands/agent.py
> feat(cli): add chat interface

- agents/community/autogen-agents/src/autogen_agents/server.py
- apps/beeai-cli/src/beeai_cli/async_typer.py
- apps/beeai-cli/src/beeai_cli/commands/agent.py
> feat(cli): render examples and add custom greetings

- agents/official/composition/src/composition/prompted_sequential_workflow.py
- apps/beeai-cli/src/beeai_cli/__init__.py
- apps/beeai-cli/src/beeai_cli/commands/agent.py
- apps/beeai-cli/src/beeai_cli/commands/compose.py
- apps/beeai-cli/src/beeai_cli/utils.py
> feat(cli): add sequential workflow ui

- apps/beeai-web/package.json
- apps/beeai-web/src/components/MainNav/MainNav.module.scss
- apps/beeai-web/src/components/MainNav/MainNav.tsx
- pnpm-lock.yaml
Refs: https://github.com/i-am-bee/beeai/issues/312
> feat(web): add Docs link

- apps/beeai-server/src/beeai_server/services/mcp_proxy/proxy_server.py
- apps/beeai-server/src/beeai_server/telemetry.py
- apps/beeai-server/src/beeai_server/utils/id.py
> chore(telemetry): add semi-stable instance id

- apps/beeai-ui/src/modules/compose/components/ComposeSetup.tsx
- apps/beeai-ui/src/modules/compose/sequential-workflow.ts
- apps/beeai-ui/src/modules/run/api/mutations/useRunAgent.tsx
- apps/beeai-ui/src/modules/run/contexts/hands-off/HandsOffProvider.tsx
- apps/beeai-ui/src/modules/run/contexts/hands-off/hands-off-context.ts
- apps/beeai-ui/src/modules/run/hands-off/HandsOffInput.tsx
Closes: https://github.com/i-am-bee/beeai/issues/316
Also fixes wrong imports of Agent type.
> feat(ui): add custom user message on hands-off ui

- apps/beeai-ui/src/components/FiltersPopover/FiltersPopover.module.scss
- apps/beeai-ui/src/components/FiltersPopover/FiltersPopover.tsx
- apps/beeai-ui/src/modules/agents/components/AgentsFilters.module.scss
- apps/beeai-ui/src/modules/agents/components/AgentsFilters.tsx
- apps/beeai-ui/src/modules/agents/hooks/useFilteredAgents.ts
- apps/beeai-ui/src/modules/agents/providers/AgentsFiltersProvider.tsx
- apps/beeai-ui/src/styles/components/_checkbox.scss
- apps/beeai-ui/src/styles/components/_index.scss
- apps/beeai-ui/src/styles/components/_link.scss
- apps/beeai-ui/src/styles/components/_popover.scss
- apps/beeai-ui/src/utils/agents/countOccurrences.ts
Refs: https://github.com/i-am-bee/beeai/issues/177
- **Groups** Agents by Framework, Language, License.
- Shows **counts** for each group.
- Button to Toggle (show/hide popover) is **highlighted** when any filter from the groups is active.
- **Synced** with label filters (under the input) back and forth (between labels and popover one way or other).
- Can click on **either** checkbox or label to toggle.
- Closes on click **outside**.
- Option to **"Clear all"** group filters (automatically closes on click).
<br>
https://github.com/user-attachments/assets/74ac4ec6-ded1-4af5-bc38-09eed3844329
> feat(ui): advanced filter for agent list

- apps/beeai-ui/src/modules/home/components/GettingStarted.module.scss
- apps/beeai-ui/src/modules/home/components/GettingStarted.tsx
Refs: https://github.com/i-am-bee/beeai/issues/312
Updating **description**.
To improve text flow, following are on the same line:  
- "and compose" (any screen)
- "discover, run, and compose" (small screen) (**Note:** 3 actions)
- "AI agents" (any screen)
- "from any framework" (any screen)
<br>
<br>
> chore(ui): update description

- apps/beeai-ui/src/modules/agents/components/AgentsFilters.module.scss
Refs: https://github.com/i-am-bee/beeai/issues/177
Resolves: https://github.com/i-am-bee/beeai/pull/311#issuecomment-2713174194
<br>
NOT Focused:
Focused:
> fix(ui): add right padding to the Search input

- apps/beeai-server/src/beeai_server/application.py
- apps/beeai-server/src/beeai_server/services/mcp_proxy/proxy_server.py
> chore(server): add metrics for providers and duration

- apps/beeai-ui/src/modules/home/components/GettingStarted.module.scss
- apps/beeai-ui/src/modules/home/components/GettingStarted.tsx
- apps/beeai-ui/src/utils/constants.ts
Refs: https://github.com/i-am-bee/beeai/issues/312
> chore(ui): update brew command

- README.md
minor suggested enhancements to primary README
> docs(README): Update README.md

- apps/beeai-server/src/beeai_server/services/mcp_proxy/proxy_server.py
> fix(sever): duration metrics collection

- docs/acp/pre-alpha/specification.mdx
- docs/docs.json
> feat(docs): pre-alpha specs

- apps/beeai-ui/src/components/UserNav/UserNav.tsx
- apps/beeai-ui/src/modules/agents/components/AgentDetail.tsx
- apps/beeai-ui/src/modules/agents/components/AgentMetadata.module.scss
- apps/beeai-ui/src/modules/agents/components/AgentMetadata.tsx
- apps/beeai-ui/src/pages/Settings.tsx
- apps/beeai-ui/src/styles/components/_checkbox.scss
- apps/beeai-ui/src/styles/components/_overflow-menu.scss
- apps/beeai-web/next.config.ts
- apps/beeai-web/src/app/agents/AgentsFilteredView.tsx
- apps/beeai-web/src/app/agents/page.tsx
Closes: https://github.com/i-am-bee/beeai/issues/348
> feat(ui): local app improvements

- apps/beeai-ui/src/modules/compose/contexts/ComposeProvider.tsx
- apps/beeai-ui/src/modules/compose/sequential/SequentialSetup.tsx
- apps/beeai-ui/src/modules/run/components/AgentHeader.tsx
- apps/beeai-ui/src/modules/run/hands-off/HandsOffText.tsx
- apps/beeai-ui/src/styles/components/_popover.scss
Fixing:
- compose result returned "undefined" as string
- new session button tooltip was not fully visible
- download button in hands-off ui had bad filename
> fix(ui): various ui fixes

- apps/beeai-web/next.config.ts
- apps/beeai-web/src/app/agents/[name]/page.tsx
- apps/beeai-web/src/app/agents/page.tsx
> chore(web): ISR and cache headers for agents

- agents/community/aider-agent/src/aider_agent/agent.py
- agents/community/autogen-agents/src/autogen_agents/server.py
- agents/community/crewai-agents/src/crewai_agents/server.py
- agents/official/agent-docs-creator/src/agent-docs-creator.ts
- agents/official/beeai-framework/src/podcast-creator/podcast-creator.ts
> chore(agents): user greeting copy update

- apps/beeai-server/src/beeai_server/application.py
- apps/beeai-server/src/beeai_server/utils/fastapi.py
> fix(server): disable browser cache for static files

- apps/beeai-server/src/beeai_server/domain/model.py
> Revert "fix(beeai-server): brew node path"

- apps/beeai-ui/src/api/mcp-client/useCreateMCPClient.ts
- apps/beeai-ui/src/contexts/MCPClient/MCPClientProvider.tsx
- apps/beeai-ui/src/contexts/MCPClient/mcp-client-context.ts
- apps/beeai-ui/src/modules/agents/api/types.ts
- apps/beeai-ui/src/modules/compose/types.ts
- apps/beeai-ui/src/modules/run/api/mutations/useRunAgent.tsx
- apps/beeai-ui/src/modules/run/api/types.ts
- apps/beeai-ui/src/modules/tools/api/types.ts
- apps/beeai-web/src/acp/client.ts
- docs/acp/pre-alpha/sdk.mdx
- packages/acp-typescript-sdk/package.json
- packages/acp-typescript-sdk/src/index.ts
- setup proper exports fields (especially missing wildcards), validate against https://arethetypeswrong.github.io
> refactor: update exports in ACP TS SDK

- apps/beeai-web/Dockerfile
> fix(web): copy of public directory

- apps/beeai-ui/src/components/layouts/AppFooter.tsx
- apps/beeai-ui/src/modules/home/components/VideoBeeAI.tsx
- apps/beeai-web/src/layouts/AppLayout.module.scss
- apps/beeai-web/src/layouts/AppLayout.tsx
- apps/beeai-web/src/layouts/MainContent.module.scss
- apps/beeai-web/src/layouts/MainContent.tsx
- remove the dark mode button
- autoplay video
- icons under the content if not enough space
> feat(web): autoplay video, footer style update

- apps/beeai-server/src/beeai_server/services/provider.py
> fix(server): allow removing providers when manifest is not found

- .github/workflows/agents.yml
> feat(agents): add workflow for building agents

- agents/official/agent-docs-creator/package-lock.json
- agents/official/agent-docs-creator/package.json
- agents/official/agent-docs-creator/src/instrumentation.ts
- agents/official/agent-docs-creator/src/server.ts
- agents/official/beeai-framework/package-lock.json
- agents/official/beeai-framework/package.json
- agents/official/beeai-framework/src/chat/chat.ts
- agents/official/beeai-framework/src/instrumentation.ts
- agents/official/beeai-framework/src/server.ts
The last PR, where I implemented the openinference instrumentation for our beeai-framework. 
Closes: https://github.com/i-am-bee/beeai-framework/issues/629
> feat(instrumentation): implement openinference for beeai

- packages/acp-python-sdk/src/acp/server/highlevel/agents/agent_manager.py
- packages/beeai-sdk/package.json
- packages/beeai-sdk/pyproject.toml
- packages/beeai-sdk/src/beeai_sdk/providers/agent.py
- uv.lock
https://github.com/orgs/i-am-bee/projects/11/views/6?pane=issue&itemId=103300223&issue=i-am-bee%7Cbeeai%7C452
https://github.com/orgs/i-am-bee/projects/11/views/6?pane=issue&itemId=103300109&issue=i-am-bee%7Cbeeai%7C451
> Agent self registration

- README.md
Depends on:
https://github.com/i-am-bee/beeai/pull/490
> docs(README): Add LF badge & text

- apps/beeai-cli/src/beeai_cli/commands/env.py
- apps/beeai-server/src/beeai_server/bootstrap.py
- apps/beeai-server/src/beeai_server/configuration.py
- apps/beeai-server/src/beeai_server/domain/model.py
- mise.lock
> feat(beeai-server): spawn Lima VM

- apps/beeai-cli/pyproject.toml
- apps/beeai-cli/src/beeai_cli/api.py
- apps/beeai-cli/src/beeai_cli/async_typer.py
- apps/beeai-cli/src/beeai_cli/commands/env.py
- apps/beeai-cli/src/beeai_cli/console.py
- uv.lock
- detect local process and its creation time
- wait for server startup if it's recently spawned
- wait for API in cases where it may not be available yet
> feat(beeai-cli): improve beeai-server waiting and management

- agents/community/ollama-deep-researcher/pyproject.toml
- agents/community/ollama-deep-researcher/src/ollama_deep_researcher/configuration.py
- agents/community/ollama-deep-researcher/src/ollama_deep_researcher/graph.py
- agents/community/ollama-deep-researcher/src/ollama_deep_researcher/server.py
- agents/community/ollama-deep-researcher/uv.lock
Not sure what was the intention of the current solution, I just simplified it to use pydantic-settings.
> fix(ollama-deep-researcher): env loading

- agent-registry.yaml
- agents/community/aider/agent.yaml
- agents/community/aider/pyproject.toml
- agents/community/aider/uv.lock
- agents/community/gpt-researcher/agent.yaml
- agents/community/gpt-researcher/pyproject.toml
- agents/community/gpt-researcher/uv.lock
- agents/community/literature-review/agent.yaml
- agents/community/literature-review/pyproject.toml
- agents/community/literature-review/src/literature_review/server.py
- agents/community/literature-review/uv.lock
- agents/community/marketing-strategy/agent.yaml
- agents/community/marketing-strategy/pyproject.toml
- agents/community/marketing-strategy/uv.lock
- agents/community/ollama-deep-researcher/agent.yaml
- agents/community/ollama-deep-researcher/pyproject.toml
- agents/community/ollama-deep-researcher/src/ollama_deep_researcher/server.py
- agents/community/ollama-deep-researcher/uv.lock
- agents/community/open-deep-research-agent/open_deep_research_agent/server.py
- agents/community/open-deep-research-agent/pyproject.toml
- agents/community/open-deep-research-agent/uv.lock
- agents/official/agent-docs-creator/agent.yaml
- agents/official/beeai-supervisor/agent.yaml
- agents/official/sequential-workflow/agent.yaml
- agents/official/sequential-workflow/pyproject.toml
- agents/official/sequential-workflow/uv.lock
- packages/beeai-sdk/src/beeai_sdk/providers/agent.py
After: https://github.com/i-am-bee/beeai/pull/519
> fix: agent's output type

- apps/beeai-server/src/beeai_server/bootstrap.py
- docs/introduction/installation.mdx
Some compatibility adjustments for WSL2 + instructions on the Installation page: https://ibm-8c0b5b62-janpokorny-feat-add-wsl-support.mintlify.app/introduction/installation
> feat: add WSL2 support

- apps/beeai-server/src/beeai_server/bootstrap.py
Check validity of the docker socket without relying on a CLI. Also adds support for other protocols than unix socket.
> fix(beeai-server): bootstrap

- apps/beeai-cli/pyproject.toml
- apps/beeai-server/pyproject.toml
- uv.lock
> bump: beeai-server and beeai-cli

- docs/introduction/installation.mdx
> docs: update brew installation instructions

- agents/community/aider/Dockerfile
- agents/community/aider/README.md
- agents/community/aider/pyproject.toml
- agents/community/aider/src/aider_agent/agent.py
- agents/community/aider/uv.lock
- agents/community/gpt-researcher/Dockerfile
- agents/community/literature-review/Dockerfile
- agents/community/marketing-strategy/Dockerfile
- agents/community/ollama-deep-researcher/Dockerfile
- agents/community/open-deep-research-agent/Dockerfile
- agents/official/beeai-framework/agent-docs-creator/Dockerfile
- agents/official/beeai-framework/chat/Dockerfile
- agents/official/beeai-framework/podcast-creator/Dockerfile
- agents/official/sequential-workflow/Dockerfile
- apps/beeai-cli/src/beeai_cli/commands/agent.py
- Port Aider agent to the new ACP SDK
- Update BeeAI CLI to support `--dump-files` again
- Update and simplify Dockerfile (we can apply this for other projects too)
> feat(aider-agent): update to new MCP SDK

- agents/official/beeai-framework/agent-docs-creator/pyproject.toml
- agents/official/beeai-framework/agent-docs-creator/src/agent_docs_creator/agent.py
- agents/official/beeai-framework/agent-docs-creator/uv.lock
- agents/official/beeai-framework/chat/pyproject.toml
- agents/official/beeai-framework/chat/src/chat/agent.py
- agents/official/beeai-framework/chat/uv.lock
- agents/official/beeai-framework/podcast-creator/pyproject.toml
- agents/official/beeai-framework/podcast-creator/src/podcast_creator/agent.py
- agents/official/beeai-framework/podcast-creator/uv.lock
Openinference instrumentation for our python beeai agents.
> feat(acp): add instrumentation for beeai

- apps/beeai-ui/src/components/layouts/Navigation.tsx
- apps/beeai-ui/src/modules/compose/contexts/ComposeProvider.tsx
- apps/beeai-ui/src/modules/compose/sequential/constants.ts
- apps/beeai-ui/src/modules/compose/types.ts
- apps/beeai-ui/src/modules/runs/api/types.ts
- apps/beeai-ui/src/modules/runs/chat/ChatInput.tsx
- apps/beeai-ui/src/modules/runs/chat/types.ts
- apps/beeai-ui/src/modules/runs/contexts/chat/ChatProvider.tsx
- apps/beeai-ui/src/modules/runs/contexts/hands-off/HandsOffProvider.tsx
- apps/beeai-ui/src/modules/runs/hooks/useRunAgent.ts
- apps/beeai-ui/src/modules/runs/utils.ts
Refs: https://github.com/i-am-bee/beeai-platform/issues/571
> feat(ui): update compose provider

- apps/beeai-ui/src/index.ts
- apps/beeai-ui/src/modules/agents/api/types.ts
- apps/beeai-web/src/utils/fetchAgentMetadata.ts
> fix(web): do not use beeai-sdk

- apps/beeai-cli/src/beeai_cli/commands/env.py
- apps/beeai-server/pyproject.toml
- apps/beeai-server/src/beeai_server/application.py
- apps/beeai-server/src/beeai_server/domain/provider/model.py
- apps/beeai-server/src/beeai_server/routes/llm.py
- uv.lock
- add a LLM gateway to beeai-server
- wire all agents to use the LLM gateway
- connect the gateway to the existing env var setup system (temp solution until we have a proper DB for storing per-user settings)
- add watsonx support
- add RITS support
> feat(llm-gateway): implement

- apps/beeai-ui/.env.example
- apps/beeai-ui/src/components/layouts/AppSidebar.tsx
- apps/beeai-ui/src/utils/feature-flags.ts
- apps/beeai-ui/src/utils/vite-constants.ts
- apps/beeai-ui/src/vite-env.d.ts
- apps/beeai-ui/vite.config.ts
Simplify feature-flags parsing and make it:
- strongly-typed
- schema-first
- immutable
- fail-fast
> chore: simplify feature-flags parsing

- apps/beeai-ui/src/modules/runs/chat/Chat.module.scss
- apps/beeai-ui/src/modules/runs/chat/Chat.tsx
- apps/beeai-ui/src/modules/runs/components/AgentHeader.tsx
- apps/beeai-ui/src/modules/runs/components/AgentIcon.tsx
- apps/beeai-ui/src/modules/runs/components/AgentModel.module.scss
- apps/beeai-ui/src/modules/runs/components/AgentModel.tsx
- apps/beeai-ui/src/modules/runs/components/InputBar.module.scss
- apps/beeai-ui/src/modules/runs/components/InputBar.tsx
- apps/beeai-ui/src/modules/runs/hands-off/HandsOff.module.scss
- apps/beeai-ui/src/modules/runs/hands-off/HandsOff.tsx
- apps/beeai-ui/src/modules/runs/utils.ts
- apps/beeai-ui/src/utils/constants.ts
> feat(ui): display agent model, update chat landing

- apps/beeai-ui/src/components/AgentsNav/AgentsNav.tsx
- apps/beeai-ui/src/components/AppHeader/AppHeader.tsx
- apps/beeai-ui/src/modules/agents/api/types.ts
- apps/beeai-ui/src/modules/agents/components/AgentDetailPanel.tsx
- apps/beeai-ui/src/modules/agents/components/AgentGreeting.module.scss
- apps/beeai-ui/src/modules/agents/components/AgentGreeting.tsx
- apps/beeai-ui/src/modules/agents/utils.ts
- apps/beeai-ui/src/modules/runs/chat/Chat.module.scss
- apps/beeai-ui/src/modules/runs/chat/Chat.tsx
- apps/beeai-ui/src/modules/runs/components/AgentHeader.tsx
- apps/beeai-ui/src/modules/runs/hands-off/HandsOff.module.scss
- apps/beeai-ui/src/modules/runs/hands-off/HandsOff.tsx
> feat(ui): use updated agent metadata fields

- apps/beeai-ui/src/components/UserNav/UserNav.tsx
- apps/beeai-ui/src/contexts/Theme/ThemeProvider.tsx
- apps/beeai-ui/src/contexts/Theme/theme-context.ts
- apps/beeai-ui/src/modules/agents/components/AgentDetailPanel.tsx
- apps/beeai-ui/src/modules/settings/ThemeView.tsx
- apps/beeai-ui/src/pages/Settings.tsx
- apps/beeai-ui/src/utils/constants.ts
> feat(ui): user nav updates, theme to settings page

- apps/beeai-cli/src/beeai_cli/__init__.py
- apps/beeai-cli/src/beeai_cli/api.py
- apps/beeai-cli/src/beeai_cli/async_typer.py
- apps/beeai-cli/src/beeai_cli/commands/agent.py
- apps/beeai-cli/src/beeai_cli/commands/build.py
- apps/beeai-cli/src/beeai_cli/commands/env.py
- apps/beeai-cli/src/beeai_cli/commands/platform.py
- apps/beeai-cli/src/beeai_cli/configuration.py
- apps/beeai-cli/src/beeai_cli/utils.py
- helm/beeai-platform/values.yaml
- pyproject.toml
> fix(beeai-cli): fix linting errors, add min memory for beeai-server

- apps/beeai-ui/src/components/FiltersPopover/FiltersPopover.tsx
- apps/beeai-ui/src/modules/home/components/GettingStarted.module.scss
- apps/beeai-ui/src/utils/constants.ts
- apps/beeai-web/src/modules/home/ExperienceShowcase.tsx
Refs: https://github.com/i-am-bee/beeai-platform/issues/570#issuecomment-2912774625
> feat(web): reduce paddings on landing page

- docs/package.json
- pnpm-lock.yaml
Fixes https://github.com/advisories/GHSA-8cj5-5rvv-wf4v
> chore: audit packages

- apps/beeai-ui/src/modules/agents/components/AgentTags.tsx
> feat(ui): display agent tags from metadata

- apps/beeai-server/src/beeai_server/infrastructure/kubernetes/provider_deployment_manager.py
> fix(platform): increase k8s probes due to some agents crashing

- apps/beeai-cli/src/beeai_cli/commands/agent.py
> feat: add agents await functionality to the CLI

- apps/beeai-cli/src/beeai_cli/commands/build.py
Add --push flag to the build command to improve multi-platform support.
Ref: #777
> feat: add --push flag to the build command

- apps/beeai-ui/src/pages/Landing.tsx
Closes: https://github.com/i-am-bee/beeai-platform/issues/770
> fix(ui): default agent

- apps/beeai-ui/src/components/MarkdownContent/components/Img.module.scss
- apps/beeai-ui/src/components/MarkdownContent/components/Img.tsx
- apps/beeai-ui/src/components/MarkdownContent/components/index.ts
- apps/beeai-ui/src/modules/compose/contexts/ComposeProvider.tsx
- apps/beeai-ui/src/modules/runs/chat/Message.tsx
- apps/beeai-ui/src/modules/runs/contexts/chat/ChatProvider.tsx
- apps/beeai-ui/src/modules/runs/contexts/hands-off/HandsOffProvider.tsx
- apps/beeai-ui/src/modules/runs/files/components/FileCard.tsx
- apps/beeai-ui/src/modules/runs/utils.ts
- apps/beeai-ui/src/utils/helpers.ts
- apps/beeai-ui/src/utils/markdown.ts
> feat(ui): add better handling for artifacts and image files

- docs/introduction/installation.mdx
Do not merge before releasing the WSL improvements.
> docs: WSL update

- .github/workflows/beeai-cli.yml
- apps/beeai-cli/tasks.toml
> fix(ci): use GITHUB_TOKEN + properly fail

- agents/community/business-case-assistant/.dockerignore
- agents/community/business-case-assistant/Dockerfile
- agents/community/business-case-assistant/README.md
- agents/community/business-case-assistant/pyproject.toml
- agents/community/business-case-assistant/src/business_case_assistant/agent.py
- agents/community/business-case-assistant/src/business_case_assistant/configuration.py
- agents/community/business-case-assistant/src/business_case_assistant/graph.py
- agents/community/business-case-assistant/src/business_case_assistant/langgraph.json
- agents/community/business-case-assistant/src/business_case_assistant/nodes.py
- agents/community/business-case-assistant/uv.lock
An agent that helps users draft a business case document using langgraph and beeai
> Adding Business Case agent to community

- apps/beeai-cli/src/beeai_cli/commands/platform.py
> fix(beeai-cli): fix `kubectl` and `limactl` behavior in certain cases

- apps/beeai-cli/src/beeai_cli/commands/env.py
- apps/beeai-cli/src/beeai_cli/commands/platform.py
- apps/beeai-cli/tasks.toml
- helm/beeai-platform/templates/collector/phoenix.yaml
- helm/beeai-platform/templates/deployment.yaml
- helm/beeai-platform/values.yaml
- helm/tasks.toml
- use `hostNetwork: true` for local k3s deployment
- use mirrored networking mode for WSL
Unifies the networking between Lima and WSL, makes WSL networking predictable, allows functioning on both Windows and WSL sides.
> feat(beeai-cli): improve platform networking

- apps/beeai-ui/src/modules/runs/components/AgentRun.tsx
Simplify the `<AgentRun>` component by replacing nested ternaries with clear `if` statements.
> refactor(ui): agent run

- apps/beeai-server/src/beeai_server/bootstrap.py
- apps/beeai-server/src/beeai_server/configuration.py
- apps/beeai-server/src/beeai_server/infrastructure/kubernetes/default_templates/deployment.yaml
- apps/beeai-server/src/beeai_server/infrastructure/kubernetes/default_templates/secret.yaml
- apps/beeai-server/src/beeai_server/infrastructure/kubernetes/default_templates/service.yaml
- apps/beeai-server/src/beeai_server/infrastructure/kubernetes/provider_deployment_manager.py
- helm/beeai-platform/templates/agent/deployment.yaml
- helm/beeai-platform/templates/config/provider_templates.yaml
- helm/beeai-platform/templates/deployment.yaml
- helm/beeai-platform/values.yaml
> feat(server): extract provider manifests into separate templates

- apps/beeai-ui/src/components/CodeSnippet/CodeSnippet.tsx
- apps/beeai-ui/src/components/CopyButton/CopyButton.tsx
- apps/beeai-ui/src/components/MarkdownContent/components/Code.tsx
- apps/beeai-ui/src/modules/runs/files/components/FileCard.module.scss
- apps/beeai-ui/src/modules/runs/files/constants.ts
- apps/beeai-ui/src/modules/runs/files/contexts/FileUploadProvider.tsx
- apps/beeai-ui/src/modules/runs/hands-off/HandsOffOutputView.module.scss
- apps/beeai-ui/src/modules/runs/hands-off/HandsOffOutputView.tsx
- apps/beeai-ui/src/modules/runs/hands-off/HandsOffText.tsx
- apps/beeai-ui/src/modules/runs/trajectory/components/MessageTrajectories.tsx
- apps/beeai-ui/src/modules/runs/trajectory/components/TrajectoryView.module.scss
- apps/beeai-ui/src/modules/runs/trajectory/components/TrajectoryView.tsx
- apps/beeai-ui/src/modules/runs/utils.ts
Refs: https://github.com/i-am-bee/beeai-platform/pull/882, https://github.com/i-am-bee/beeai-platform/pull/874, https://github.com/i-am-bee/beeai-platform/pull/907
> feat(ui): small ui improvs

- apps/beeai-cli/src/beeai_cli/commands/platform.py
- helm/templates/collector/service.yaml
- helm/templates/docling/docling-serve.yaml
- helm/templates/ui/deployment.yaml
- helm/values.yaml
- use k3s LoadBalancer for most services except beeai-server which actually needs hostNetwork to access local resources (Ollama, local agents)
- on WSL, create systemd units with kubectl port-forward to forward LoadBalancer services to 127.0.0.1 -- as k3s can't bind to localhost itself
> fix: WSL networking

- agents/a2a-ui-test/hello/src/extensions.py
- apps/beeai-ui/src/modules/agents/api/types.ts
- apps/beeai-ui/src/modules/agents/components/AgentCredits.module.scss
- apps/beeai-ui/src/modules/agents/components/AgentCredits.tsx
- apps/beeai-ui/src/modules/agents/components/AgentDetailPanel.module.scss
- apps/beeai-ui/src/modules/agents/components/AgentDetailPanel.tsx
- apps/beeai-ui/src/modules/agents/components/AgentMetadataView.tsx
- apps/beeai-ui/src/modules/agents/utils.ts
- apps/beeai-web/src/modules/agents/AgentDetail.tsx
> feat(ui): align agent ui fields, add author and contributors

- apps/beeai-ui/src/modules/agents/components/AgentDetailPanel.module.scss
- apps/beeai-ui/src/modules/agents/components/AgentDetailPanel.tsx
- apps/beeai-ui/src/modules/agents/utils.ts
Closes: https://github.com/i-am-bee/beeai-platform/issues/968
> feat(ui): show only source code link in agent's panel

- agents/ui/hello/src/extensions.py
- agents/ui/hello/src/main.py
- agents/ui/hello/src/sdk.py
- apps/beeai-ui/src/api/schema.d.ts
- apps/beeai-ui/src/components/AgentsNav/AgentsNav.tsx
- apps/beeai-ui/src/components/AppHeader/AppHeader.tsx
- apps/beeai-ui/src/modules/agents/api/types.ts
- apps/beeai-ui/src/modules/agents/components/AgentCredits.tsx
- apps/beeai-ui/src/modules/agents/components/AgentDetailPanel.tsx
- apps/beeai-ui/src/modules/agents/components/AgentGreeting.tsx
- apps/beeai-ui/src/modules/agents/components/AgentHeading.tsx
- apps/beeai-ui/src/modules/agents/components/AgentMetadataView.tsx
- apps/beeai-ui/src/modules/agents/components/AgentTags.tsx
- apps/beeai-ui/src/modules/agents/components/ImportAgentsModal.tsx
- apps/beeai-ui/src/modules/agents/hooks/useFilteredAgents.ts
- apps/beeai-ui/src/modules/agents/utils.ts
- apps/beeai-ui/src/modules/compose/components/AgentListOption.tsx
- apps/beeai-ui/src/modules/compose/components/ComposeStepListItem.tsx
- apps/beeai-ui/src/modules/providers/hooks/useMonitorProviderStatus.ts
- apps/beeai-ui/src/modules/runs/chat/ChatInput.tsx
- apps/beeai-ui/src/modules/runs/chat/Message.tsx
- apps/beeai-ui/src/modules/runs/components/AgentRun.tsx
- apps/beeai-ui/src/modules/runs/constants.ts
- apps/beeai-ui/src/modules/runs/hands-off/HandsOffInput.tsx
- apps/beeai-ui/tasks.toml
- apps/beeai-web/src/modules/agents/AgentDetail.tsx
> feat(ui): sync agent details extension with beeai-sdk

- apps/beeai-server/src/beeai_server/api/dependencies.py
- apps/beeai-server/src/beeai_server/api/routes/user_feedback.py
- apps/beeai-server/src/beeai_server/api/schema/user_feedback.py
- apps/beeai-server/src/beeai_server/application.py
- apps/beeai-server/src/beeai_server/domain/models/user_feedback.py
- apps/beeai-server/src/beeai_server/domain/repositories/user_feedback.py
- apps/beeai-server/src/beeai_server/infrastructure/persistence/migrations/alembic/versions/b2d91792f9b5_.py
- apps/beeai-server/src/beeai_server/infrastructure/persistence/repositories/user_feedback.py
- apps/beeai-server/src/beeai_server/infrastructure/persistence/unit_of_work.py
- apps/beeai-server/src/beeai_server/service_layer/services/user_feedback.py
- apps/beeai-server/src/beeai_server/service_layer/unit_of_work.py
- apps/beeai-server/tasks.toml
Example curl for testing:
```bash
curl -X POST http://localhost:18333/api/v1/user_feedback \
-H "Content-Type: application/json" \
-d '{
"provider_id": "2228694e-0b87-1f5d-f999-d413096510d4",
"task_id": "2228694e-0b87-1f5d-f999-d413096510d4",
"context_id": "2228694e-0b87-1f5d-f999-d413096510d4",
"rating": 1,
"message": "Message from LLM",
"comment": "I didnt like it",
"comment_tags": ["performance", "accuracy"]
}'
```
> feat: backend for user feedback

- agents/official/sequential-workflow/src/sequential_workflow/agent.py
- agents/official/sequential-workflow/uv.lock
- apps/beeai-ui/src/api/a2a/client.ts
- apps/beeai-ui/src/api/a2a/types.ts
- apps/beeai-ui/src/api/a2a/utils.ts
- apps/beeai-ui/src/modules/compose/a2a/extensions/sequential-workflow.ts
- apps/beeai-ui/src/modules/compose/a2a/types.ts
- apps/beeai-ui/src/modules/compose/a2a/utils.ts
- apps/beeai-ui/src/modules/compose/components/ComposeStepListItem.module.scss
- apps/beeai-ui/src/modules/compose/components/ComposeStepListItem.tsx
- apps/beeai-ui/src/modules/compose/components/StepResult.tsx
- apps/beeai-ui/src/modules/compose/contexts/ComposeProvider.tsx
- apps/beeai-ui/src/modules/compose/contexts/compose-context.tsx
- apps/beeai-ui/src/modules/compose/sequential/SequentialSetup.tsx
- apps/beeai-ui/src/modules/compose/types.ts
- apps/beeai-ui/src/modules/messages/types.ts
- apps/beeai-ui/src/modules/messages/utils.ts
- apps/beeai-ui/src/modules/runs/contexts/agent-run/AgentRunProvider.tsx
- apps/beeai-ui/tasks.toml
- apps/beeai-ui/tsconfig.check.json
- apps/beeai-ui/tsconfig.json
> feat(ui): update sequential workflow to a2a

- apps/beeai-ui/package.json
- apps/beeai-ui/src/api/schema.d.ts
- apps/beeai-ui/src/components/CopyButton/CopyButton.tsx
- apps/beeai-ui/src/contexts/Toast/ToastProvider.tsx
- apps/beeai-ui/src/contexts/Toast/toast-context.ts
- apps/beeai-ui/src/modules/feedback/api/index.ts
- apps/beeai-ui/src/modules/feedback/api/mutations/useSendFeedback.ts
- apps/beeai-ui/src/modules/feedback/api/types.ts
- apps/beeai-ui/src/modules/feedback/api/utils.ts
- apps/beeai-ui/src/modules/feedback/components/FeedbackForm.module.scss
- apps/beeai-ui/src/modules/feedback/components/FeedbackForm.tsx
- apps/beeai-ui/src/modules/feedback/components/MessageFeedback.module.scss
- apps/beeai-ui/src/modules/feedback/components/MessageFeedback.tsx
- apps/beeai-ui/src/modules/feedback/constants.ts
- apps/beeai-ui/src/modules/feedback/hooks/useFeedback.ts
- apps/beeai-ui/src/modules/feedback/types.ts
- apps/beeai-ui/src/modules/messages/components/MessageActions.module.scss
- apps/beeai-ui/src/modules/messages/components/MessageActions.tsx
- apps/beeai-ui/src/modules/runs/chat/ChatAgentMessage.module.scss
- apps/beeai-ui/src/modules/runs/chat/ChatAgentMessage.tsx
- apps/beeai-ui/src/modules/runs/chat/ChatMessagesView.module.scss
- apps/beeai-ui/src/modules/runs/chat/ChatMessagesView.tsx
- apps/beeai-ui/src/modules/runs/contexts/agent-run/AgentRunProvider.tsx
- apps/beeai-ui/src/modules/runs/contexts/agent-run/agent-run-context.ts
- apps/beeai-ui/src/styles/components/_index.scss
- apps/beeai-ui/src/styles/components/_notification.scss
- apps/beeai-ui/src/styles/components/_text-area.scss
- pnpm-lock.yaml
Closes: https://github.com/i-am-bee/beeai-platform/issues/716
> feat(ui): add message feedback

- apps/beeai-sdk/src/beeai_sdk/a2a/extensions/services/mcp.py
Signed-off-by: Tomas Pilar <thomas7pilar@gmail.com>
> fix(sdk): remove override to support python 3.11

- docs/community-and-support/acp-a2a-migration-guide.mdx
Fixed my agent URL since I merged a2a code to main
> docs: Update acp-a2a-migration-guide.mdx

- apps/beeai-cli/uv.lock
- apps/beeai-sdk/examples/cli.py
- apps/beeai-sdk/examples/mcp_client.py
- apps/beeai-sdk/pyproject.toml
- apps/beeai-sdk/src/beeai_sdk/a2a/extensions/auth/oauth/oauth.py
- apps/beeai-sdk/src/beeai_sdk/a2a/extensions/services/embedding.py
- apps/beeai-sdk/src/beeai_sdk/a2a/extensions/services/llm.py
- apps/beeai-sdk/src/beeai_sdk/a2a/extensions/services/mcp.py
- apps/beeai-sdk/src/beeai_sdk/a2a/extensions/ui/agent_detail.py
- apps/beeai-sdk/src/beeai_sdk/a2a/extensions/ui/citation.py
- apps/beeai-sdk/src/beeai_sdk/a2a/extensions/ui/trajectory.py
- apps/beeai-sdk/src/beeai_sdk/server/app.py
- apps/beeai-sdk/tests/e2e/test_runs.py
- apps/beeai-sdk/uv.lock
- apps/beeai-server/pyproject.toml
- apps/beeai-server/src/beeai_server/api/routes/a2a.py
- apps/beeai-server/tests/e2e/routes/test_a2a_proxy.py
- apps/beeai-server/uv.lock
Signed-off-by: Tomas Pilar <thomas7pilar@gmail.com>
> feat(sdk): add rest transport to the agent

- apps/beeai-cli/src/beeai_cli/__init__.py
- install.sh
Add experimental install script and `beeai upgrade` + `beeai uninstall` commands. Hidden for now, not in the docs, until we QA them.
(Maybe `beeai self upgrade` and `beeai self uninstall` would be better names, but whatever for now, they're hidden anyway.)
> feat(beeai-cli): add experimental install script

- apps/beeai-ui/src/components/UserNav/UserNav.tsx
- apps/beeai-ui/src/hooks/useBreakpoint.ts
Closes: https://github.com/i-am-bee/beeai-platform/issues/1166
> fix(ui): left sidebar overlays app settings

- apps/beeai-cli/src/beeai_cli/commands/server.py
- apps/beeai-server/src/beeai_server/api/dependencies.py
- apps/beeai-server/src/beeai_server/api/routes/auth.py
- apps/beeai-server/src/beeai_server/application.py
- apps/beeai-server/src/beeai_server/service_layer/services/auth.py
`/.well-known/oauth-protected-resource` must be placed at path's prefix
> fix(server): ensure resource protected metadata RFC compliance

- apps/beeai-cli/src/beeai_cli/commands/platform/__init__.py
- apps/beeai-cli/src/beeai_cli/commands/server.py
- apps/beeai-sdk/src/beeai_sdk/server/server.py
> fix(cli): fetch oauth resource metadata from correct path

- docs/deployment/kubernetes.mdx
I have not included OIDC configuration for clarity sake. We should eventually make it part of the advanced configuration.
> chore(docs): update k8s deployment

- agents/chat/src/chat/agent.py
closes:  #1292
closes: #1291 
- Remove `final_answer` from trajectory
- Store trajectory events in history
> fix(chat): store trajectory history, remove final_answer event
